### ISSUE TITLE
Help - pgAdmin4 fails with AttributeError: 'str' object has no attribute 'gettext'

### ISSUE THREAD

**Issue by axelhuizinga** [mrjoes/flask-babelex#14]
Starting pgAdmin 4. Please navigate to http://127.0.0.1:5050 in your browser.
2018-03-25 19:41:11,128: ERROR  werkzeug:       Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1607, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1654, in try_trigger_before_first_request_functions
    func()
  File "/usr/share/pgadmin4/web/pgadmin/utils/__init__.py", line 43, in create_module_preference
    self.register_preferences()
  File "/usr/share/pgadmin4/web/pgadmin/browser/__init__.py", line 208, in register_preferences
    gettext("Show system objects?"), 'boolean', False,
  File "/usr/local/lib/python2.7/dist-packages/flask_babelex/__init__.py", line 624, in gettext
    return get_domain().gettext(*args, **kwargs)
AttributeError: 'str' object has no attribute 'gettext'

**Comment by TaaviE** [comment]
I'm getting the same error with a different project.
